### ISSUE TITLE
Не работает, выбрасывает исключение ...Property 'websiteKey' is empty....

### ISSUE THREAD

**Issue by pavelforever** [xRubin/unapi-gsm-mts#1]
Пробовал сам написать, но даже авторизацию не удаётся реализовать. Перепробовал много разных решений на github, ни одно не работает. Ваше довольно свежее, надеюсь на него. Устанавливал с нуля в чистый проект. Могу предоставить доступ, если будет нужен.
Хотел привести код, но редактор его режет. Но там чисто строки из Вашего примера с данными (телефон, пароль, код антикапчи).
Полностью текст ошибки :
"Fatal error: Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Some of the required values for successive user emulation are missing. Property 'websiteKey' is empty in /home/admin/web/r.ru/public_html/vendor/guzzlehttp/promises/src/functions.php:112 Stack trace: #0 /home/admin/web/r.ru/public_html/vendor/guzzlehttp/promises/src/Promise.php(75): GuzzleHttp\Promise\exception_for('Some of the req...') #1 /home/admin/web/r.ru/public_html/vendor/guzzlehttp/promises/src/Promise.php(65): GuzzleHttp\Promise\Promise->wait(true) #2 /home/admin/web/r.ru/public_html/index.php(19): GuzzleHttp\Promise\Promise->wait() #3 {main} thrown in /home/admin/web/r.ru/public_html/vendor/guzzlehttp/promises/src/functions.php on line 112"

**Comment by xRubin** [comment]
Судя по ошибке, у вас не передан ключ сервиса в объект Antiсaptcha. 

```php
<?php
use unapi\gsm\mts\Service;
use unapi\gsm\mts\Anticaptcha;
use unapi\anticaptcha\antigate\AntigateService;

$service = new Service([
    'anticaptcha' => new Anticaptcha(
        new AntigateService([
            'key' => YOUR_ANTIGATE_KEY,
        ])
    )
]);
```

Решения для мтс стабильно работать не будут, очень уж ребята любят переделывать свой сайт.
